[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "google-generativeai>=0.8.5",
    "requests>=2.32.3",
    "spotipy>=2.25.1",
    "streamlit>=1.45.0",
]
